version: "3.9"

services:
  web:
    build: .
    container_name: ai_clothes_store_app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    container_name: ai_clothes_store_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: ai_clothes_store_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
