# Generated by Django 5.2 on 2025-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_item_itemimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('tshirt', 'T-Shirt'), ('shirt', 'Shirt'), ('hoodie', 'Hoodie')], max_length=100),
        ),
    ]
