# Generated by Django 5.2 on 2025-05-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_categoryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price_finish',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_start',
        ),
    ]
