# Generated by Django 5.2 on 2025-05-19 10:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_rename_price_finish_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None),
        ),
    ]
