# Generated by Django 5.2 on 2025-05-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_item_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fit',
            field=models.CharField(choices=[('slim', 'Slim'), ('standard', 'Standard'), ('loose', 'Loose'), ('oversize', 'Oversize')], default='standard', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL')], default='M', max_length=10),
            preserve_default=False,
        ),
    ]
