# Generated by Django 5.2 on 2025-08-01 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_item_fit_item_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="itemimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
