# Generated by Django 5.2 on 2025-08-28 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_itemimage_created_at_itemimage_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemEditableImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="items/editables/")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="editable_images",
                        to="catalog.item",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
